version: "3.7"
services:
  tfbstatus:
    build:
      context: .
      args:
        SKIP_TESTS: "true"
    ports:
      - "80:80"
    volumes:
      - ./managed_files:/tfbstatus/managed_files
      - ./example-config.yml:/tfbstatus/config.yml
    command: config.yml
